#include <string.h>  
#include <stdlib.h> 
#include "IPMIConf.h"     
#include "ipmi_common.h"  
#include "sensor.h"   
#include "api_sensor.h"       

FullSensorRec_T   g_sensor_sdr_main[] =
{
    	{	 /* SDR Record    0x01   "P0V9_VCORE"   SUB_DEVICE_SDR_P0V9 */
		.hdr.ID               = 0x0001,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x01,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_VOLTS,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x81,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = 0xC0,
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0x5b,
		.UpperCritical        = 0x54,
		.UpperNonCritical     = 0x4d,
		.LowerNonRecoverable  = 0x31,
		.LowerCritical        = 0x38,
		.LowerNonCritical     = 0x3f,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_P0V9,
		.IDStrTypeLen         = 0xC0 + sizeof("P0V9_VCORE"),
		.IDStr                = "P0V9_VCORE",
	},

	{	 /* SDR Record    0x02   "P2V5_VCORE"   SUB_DEVICE_SDR_P2V5 */
		.hdr.ID               = 0x0002,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x02,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_VOLTS,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x81,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = 0xC0,
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0x5b,
		.UpperCritical        = 0x54,
		.UpperNonCritical     = 0x4d,
		.LowerNonRecoverable  = 0x31,
		.LowerCritical        = 0x38,
		.LowerNonCritical     = 0x3f,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_P2V5,
		.IDStrTypeLen         = 0xC0 + sizeof("P2V5_VCORE"),
		.IDStr                = "P2V5_VCORE",
	},

	{	 /* SDR Record    0x03   "P1V2_VCORE"   SUB_DEVICE_SDR_P1V2 */
		.hdr.ID               = 0x0003,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x03,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_VOLTS,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x81,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = 0xC0,
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0x79,
		.UpperCritical        = 0x70,
		.UpperNonCritical     = 0x66,
		.LowerNonRecoverable  = 0x41,
		.LowerCritical        = 0x4a,
		.LowerNonCritical     = 0x54,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_P1V2,
		.IDStrTypeLen         = 0xC0 + sizeof("P1V2_VCORE"),
		.IDStr                = "P1V2_VCORE",
	},

	{	 /* SDR Record    0x04   "P1V8_VCORE"   SUB_DEVICE_SDR_P1V8 */
		.hdr.ID               = 0x0004,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x04,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_VOLTS,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x81,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = 0xC0,
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0xb5,
		.UpperCritical        = 0xa7,
		.UpperNonCritical     = 0x99,
		.LowerNonRecoverable  = 0x62,
		.LowerCritical        = 0x70,
		.LowerNonCritical     = 0x7e,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_P1V8,
		.IDStrTypeLen         = 0xC0 + sizeof("P1V8_VCORE"),
		.IDStr                = "P1V8_VCORE",
	},

	{	 /* SDR Record    0x05   "VBAT"   SUB_DEVICE_SDR_P3V3 */
		.hdr.ID               = 0x0005,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x05,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_VOLTS,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x27,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = 0xD0,
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0x6e,
		.UpperCritical        = 0x66,
		.UpperNonCritical     = 0x5d,
		.LowerNonRecoverable  = 0x3b,
		.LowerCritical        = 0x44,
		.LowerNonCritical     = 0x4c,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_P3V3,
		.IDStrTypeLen         = 0xC0 + sizeof("VBAT"),
		.IDStr                = "VBAT",
	},

	{	 /* SDR Record    0x06   "WORKING_TEMP"   SUB_DEVICE_SDR_TEMP */
		.hdr.ID               = 0x0006,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x06,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_DEGREES_C,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x05,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = (0x0F << 4) + (0x0 & 0x0F),
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0xC8,
		.UpperCritical        = 0xAA,
		.UpperNonCritical     = 0x96,
		.LowerNonRecoverable  = 0x00,
		.LowerCritical        = 0x00,
		.LowerNonCritical     = 0x00,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_TEMP,
		.IDStrTypeLen         = 0xC0 + sizeof("WORKING_TEMP"),
		.IDStr                = "WORKING_TEMP",
	},

	{	 /* SDR Record    0x07   "P12V"   SUB_DEVICE_SDR_P12V */
		.hdr.ID               = 0x0007,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x07,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_VOLTS,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x7a,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = 0xD0,
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0x23,
		.UpperCritical        = 0x20,
		.UpperNonCritical     = 0x1e,
		.LowerNonRecoverable  = 0x13,
		.LowerCritical        = 0x16,
		.LowerNonCritical     = 0x18,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_P12V,
		.IDStrTypeLen         = 0xC0 + sizeof("P12V"),
		.IDStr                = "P12V",
	},

	{	 /* SDR Record    0x08   "P3V3"   SUB_DEVICE_SDR_P3V3 */
		.hdr.ID               = 0x0008,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x08,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_VOLTS,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x1a,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = 0xD0,
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0xa5,
		.UpperCritical        = 0x98,
		.UpperNonCritical     = 0x8c,
		.LowerNonRecoverable  = 0x59,
		.LowerCritical        = 0x66,
		.LowerNonCritical     = 0x72,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_P3V3,
		.IDStrTypeLen         = 0xC0 + sizeof("P3V3"),
		.IDStr                = "P3V3",
	},

	{	 /* SDR Record    0x09   "CPU_TEMP"   SUB_DEVICE_SDR_TEMP */
		.hdr.ID               = 0x0009,
		.hdr.Version          = 0x51,
		.hdr.Type             = 0x01,
		.hdr.Len              = 0x40,

		.OwnerID              = 0x20,
		.OwnerLUN             = 0x00,
		.SensorNum            = 0x09,

		.EntityID             = 0x07,
		.EntityIns            = 0x03,
		.SensorInit           = 0x7F,
		.SensorCaps           = 0x68,
		.SensorType           = 0x02,
		.EventTypeCode        = 0x01,
		.AssertionEventMask   = 0x7A95,
		.DeAssertionEventMask = 0x7A95,
		.DiscreteReadingMask  = 0x3F3F,
		.Units1               = 0x20,
		.Units2               = IPMI_UNIT_DEGREES_C,
		.Units3               = 0x00,
		.Linearization        = 0x00,
		.M                    = 0x05,
		.M_Tolerance          = 0x00,
		.B                    = 0x00 & 0xff,
		.B_Accuracy           = 0x3E & 0xFF,
		.Accuracy             = 0x34,
		.R_B_Exp              = (0x0F << 4) + (0x0 & 0x0F),
		.Flags                = 0x00,
		.NominalReading       = 0x00,
		.NormalMax            = 0x00,
		.NormalMin            = 0x00,
		.MaxReading           = 0xFF,
		.MinReading           = 0x00,

		.UpperNonRecoverable  = 0xC8,
		.UpperCritical        = 0xAA,
		.UpperNonCritical     = 0x96,
		.LowerNonRecoverable  = 0x00,
		.LowerCritical        = 0x00,
		.LowerNonCritical     = 0x00,
		.PositiveHysterisis   = 0x00,
		.NegativeHysterisis   = 0x00,
		.Reserved1            = 0x00,
		.Reserved2            = 0x00,
		.OEMField             = SUB_DEVICE_SDR_TEMP,
		.IDStrTypeLen         = 0xC0 + sizeof("CPU_TEMP"),
		.IDStr                = "CPU_TEMP",
	},

};



